; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:tinypico]
platform = espressif32
board = tinypico
framework = arduino
monitor_speed = 115200

build_unflags = -D BOARD_HAS_PSRAM
build_flags = 	-mfix-esp32-psram-cache-issue

board_build.partitions = default.csv

upload_protocol = espota
upload_port = 192.168.8.242 ; Cafeteria Network.... Replace with the IP address of your ESP32 device for OTA updates
upload_flags =
    --timeout=30
    --host_port=55910 ; needs to be open in the firewall for OTA updates to work
	--auth=interface ; Set the OTA password to match the one defined in the code (ArduinoOTA.setPassword("interface");)

lib_deps = 
	majicdesigns/MD_MAX72XX@^3.3.0
	knolleary/PubSubClient@^2.8
	majicdesigns/MD_Parola@^3.5.6
	FastLED/FastLED@3.7.0
	https://github.com/tzapu/WiFiManager#e1f59eb4c5f9a2597b46f3d2ec9a70ae0297dc0d ; Use this specific commit of WiFiManager to ensure it works with WPA2 Enterprise networks like EDUROAM
